name: hello

on:
  push:
    branches:
      - master

jobs:
  hello_world:
    runs-on: ubuntu-20.04
    steps:
      - name: Hello!
        run: |
          echo "Hello world!"
      - name: Today is
        run: |
          date
      - name: dir is 
        run: |
          ls -la