on:
  push:
    branches:
      - master

  # schedule:
  #   - cron:  '15 * * * *'

jobs:
  simple_deployment_pipeline:
    runs-on: ubuntu-20.04
    steps:

      - name: check health
        uses: jtalk/url-health-check-action@v2
        with:
          url: "https://powerful-mesa-46660.herokuapp.com/health"